All files are added to Portfolio branch
Alynn9/Assignment1 pull request #1
Opened 2022-07-06 14:11 UTC by Alynn9

2022-07-07 16:23 UTC, Chrishalaby requested changes
the BEM methodology was well worked on though it still needs a bit of improvements.

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +        <div class="navBar">
use sections instead of div tags

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +            <div class="text-is-center container">
no need for the concatenated divs.

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +                <div class="container">
same as before, check the rest of the code for unneeded concatenation.

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +                    <h1>Designer</h1>
h1 tag should only be used once and followed by the rest of the headers from h2 to h5

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +                <div class="box2">
way too many divs that can be replaced with a ul tag

2022-07-07 16:23 UTC, Chrishalaby commented on Home.html
> +              <img class="text-is-centerme --modify4" src="/mf-logo2 white.svg">
always add an alt to imgs

2022-07-07 16:23 UTC, Chrishalaby commented on Home.css
> +    height: 100px;
always use rem or em in measurement

2022-07-07 16:23 UTC, Chrishalaby commented on Home.css
> +h1,h2{
dont use html tags in css

2022-07-07 16:23 UTC, Chrishalaby commented on Home.css
> +    /*.big__box{
remove comments

2022-07-08 18:01 UTC, Khousheish requested changes
good progress in general just some issues that are repeating a lot please fix them in all places as I didnt comment on every violation
also fix both files to use 2 space indentation and pay close attention to the indentation since as mentioned lots of places had added spaces and no spaces etc..

2022-07-08 18:01 UTC, Khousheish commented on Home.html
> +</html>
add EOF

2022-07-22 13:24 UTC, Chrishalaby requested changes

2022-07-22 13:24 UTC, Chrishalaby commented on Style.css
> +h1,
dont use html tags in css, applied to everywhere in ur css code

2022-07-22 13:24 UTC, Chrishalaby commented on Style.css
> +  margin-top: 30px;
change all px in spacing margin padding etc.. to rem or em

2022-07-22 13:24 UTC, Chrishalaby commented on Style.css
> +  position:absolute;
it is preferred not to use position absolute

2022-07-22 13:24 UTC, Chrishalaby commented on home.html
> +          <div class="navbar navbar__image">
div tag not needed here

2022-07-22 13:24 UTC, Chrishalaby commented on home.html
> +          <div class="navbar navbar__text">
same here no need for div, when u can apply directly the changes to the inner tags

2022-07-22 13:24 UTC, Chrishalaby commented on home.html
> +        <div class="text-is-center container">
both divs here should be removed and same idea should be applied everywhere else

2022-07-22 13:24 UTC, Chrishalaby commented on home.html
> +        <div class="__content --bottom">
work on the BEM style

2022-07-26 10:30 UTC, Chrishalaby requested changes
A lot of div tags that can be removed, recheck your whole code and work on diminishing them

2022-07-26 10:30 UTC, Chrishalaby commented on Style.css
> +.my-recent-work img {
remove all html tags from css
refer to them just by their class names

2022-07-26 10:30 UTC, Chrishalaby commented on home.html
> +    <div class= "text-is-center title-sub">
add these 2 divs into a section maybe and so there wouldnt be any use for the div tags here

2022-07-26 10:30 UTC, Chrishalaby commented on home.html
> +      <div class="title-sub --modify">
div tag can be removed here, changes can be applied to the section or the h2 ...

2022-07-26 10:30 UTC, Chrishalaby commented on home.html
> +        <div class="box__text--modify2">
why not directly apply the box text modify to the p tag instead of using a div

2022-07-26 10:30 UTC, Chrishalaby commented on home.html
> +        <div class="my-recent-work-img">
a lot of un needed div tags

2022-07-26 10:30 UTC, Chrishalaby commented on home.html
> +    <div class="above-footer">
use sections

2022-07-29 16:53 UTC, Alynn9 commented on Home.html
> +        <div class="navBar">
I used the <nav> tag in navigation bar and removed unneeded div

2022-07-29 16:53 UTC, Alynn9 commented on Home.html
> +            <div class="text-is-center container">
Div is removed

2022-07-29 16:53 UTC, Alynn9 commented on Home.html
> +                    <h1>Designer</h1>
I changed the h1 tag with h3 tag and i used h1 tag only once

2022-07-29 16:53 UTC, Alynn9 commented on Home.html
> +                <div class="box2">
I substituted the divs witg ul tags

2022-07-29 16:54 UTC, Alynn9 commented on Home.html
> +              <img class="text-is-centerme --modify4" src="/mf-logo2 white.svg">
I added the alt for all the images

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    height: 100px;
I changed all the margins and padding values into rem

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +h1,h2{
I removed all the html tags from css

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    /*.big__box{
I fixed this and the website is responsive

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    color: #cce0fa;
I created variables for the colors

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +body{
I changed home.css to Style.css

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +.navBar .navbar__image  {
I changed to lowercase.

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +.navBar  ul{
I fixed this problem

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    color:black;
I changed all the color names into variables

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    padding: 10px 10px ;
I fixed this problem when i used Ubuntu

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    position: absolute;
I used position absolute only once in above-footer class for the design

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +    margin-left: 53.75%;
I used display:flex and the problem solved

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +#twit{
I changed the ids into classes

2022-07-29 16:54 UTC, Alynn9 commented on Home.css
> +@media only screen and (min-width: 375px) and (max-width: 812px) {
I used @media (max-width :768px)

2022-07-29 16:54 UTC, Alynn9 commented on Home.html
> +</html>
The EOF is added

2022-07-29 16:55 UTC, Alynn9 commented on Style.css
> +h1,
I removed all the html tags from css

2022-07-29 16:55 UTC, Alynn9 commented on Style.css
> +  margin-top: 30px;
I changed all the margins and padding values to rem instead of px

2022-07-29 16:55 UTC, Alynn9 commented on Style.css
> +  position:absolute;
Here the only place i used position:absolute for the design

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +          <div class="navbar navbar__image">
The div tags are removed

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +          <div class="navbar navbar__text">
I removed the div tag and the class directly to image

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +        <div class="text-is-center container">
I removed the div tags

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +        <div class="__content --bottom">
I tried my best to fix the BEM style

2022-07-29 16:55 UTC, Alynn9 commented on Style.css
> +.my-recent-work img {
I rechecked and removed the div tags instead i applied them by there class name

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +      <div class="title-sub --modify">
I made the changes  and applied and used by class name

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +        <div class="box__text--modify2">
I fixed it

2022-07-29 16:55 UTC, Alynn9 commented on home.html
> +        <div class="my-recent-work-img">
I removed all the unneeded tags

2022-08-08 17:03 UTC, Chrishalaby commented on Style.css
> +}
add extra blank line

2022-08-09 21:04 UTC, Khousheish commented on Style.css
> +  margin: 0;
no actually its not 0 on the elements
this article says it best 
https://css-tricks.com/reset-all-margins-padding/

2022-08-09 21:14 UTC, Khousheish requested changes
the first half of the css file is very good but towards the end I felt you didnt apply what we discussed before
please recheck my comments and apply them to the whole file as I didnt comment on every single occurrence

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  box-sizing: border-box;
readd the 0 margin and padding

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  --fs-medium:1.25rem;
add space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  font-size:var(--fs-medium);
add space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  flex-direction: row;
you can remove this since its row by default

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  padding-top:2rem;
add space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +
remove space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +.big__box--boxSecond {
dont use camelcase in  class names

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  padding: 1rem 1rem;
can be simplified to only 1 rem

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  width: auto;
dont define auto width let it take as much as it needs

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  padding:10px;
add space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  padding:10px;
you can write this as 1 rem

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  margin-top: 10rem;
youre not following the scale from my previous discussion here

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  margin: 0 auto;
remove

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  width: 80rem;
remove random value

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  width:100%;
add space

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  width: 60rem;
remove random rem value

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  margin-right: 10rem;
follow the scale discussion we had last time
check the rest of the PR for this violation

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +  margin:2rem 0;
add space
please fix for all occurrences

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +    --fs-large: 2.25rem;
you shouldnt change the scale if the screen gets smaller as itll automatically get smaller as youre using rems

2022-08-09 21:14 UTC, Khousheish commented on Style.css
> +    margin: 0;
remove all these and readd margin and padding 0 in the *

2022-08-14 18:48 UTC, Khousheish approved these changes
some comments dont seem t o be fully addressed please recheck them and resolve the ones that are done
other than that I think its good enough to move on to the next task
@Chrishalaby please recheck from your side

2022-08-19 16:45 UTC, Chrishalaby commented on home.html
> +      <section class="big__box">
use a div here, never use a section inside another section

2022-08-19 16:45 UTC, Chrishalaby commented on home.html
> +        <div class="footer-box__icons">
is the div here needed?

2022-08-19 16:45 UTC, Chrishalaby commented on home.html
> +      <div class="above-footer--container">
can div here be removed?

2022-08-23 20:15 UTC, Chrishalaby approved these changes

2022-09-01 09:38 UTC, merged